- core/core-api/src/main/kotlin/com/myongjiway/core/api/support/error/ErrorCode.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/api/support/error/ErrorType.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorCode.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorKind.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorLevel.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorType.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreException.kt
> core-domain exception 관련 설정 추가 / core-api ErrorCode, ErrorCodeType 리팩토링
>
> [FEAT]: Core-Domain, Core-Api 모듈 공통 exception 설정

- .gitignore
- clients/client-mqtt/build.gradle.kts
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttClientConfig.kt
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/util/AwsIotUtil.kt
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/util/PrivateKeyReader.kt
- core/core-api/build.gradle.kts
- settings.gradle.kts
> MQTT 설정과 연동, 연동테스트 진행하였습니다.
> 해당 커밋에서는 certs 파일들과 yml 환경변수들이 포함되지 않았기 때문에 merge후에 설정 변경이 필요해 보입니다.
> [FEAT] MQTT 설정 및 연동 테스트

- clients/client-mqtt/build.gradle.kts
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttClientConfig.kt
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttTopic.kt
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/util/AwsIotUtil.kt
- clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/util/PrivateKeyReader.kt
- core/core-domain/src/main/kotlin/com/myongjiway/domain/buslocation/BusLocation.kt
- core/core-domain/src/main/kotlin/com/myongjiway/domain/buslocation/BusLocationService.kt
- core/core-domain/src/test/kotlin/com/myongjiway/domain/buslocation/BusLocationTest.kt
> 버스 위치 정보를 저장한다.
> 초기 서비스다 보니 map자료구조를 사용 추후 redis 고려
> [FEAT] 버스 위치 정보 저장

- .github/workflows/cd.yml
> CD.yml 을 수정하여 서버에 있는 .env를 참조하게 변경했습니다.
> 현재 구조상 develop에서 main으로 merge할 때 CD 플로우가 작동하기 때문에 로컬에 있는 .env를 자동으로 업로드할 수 없습니다.
수정 사항이 생기면 직접 서버에 접속해서 고쳐주시면 될 것 같습니다.
> [DOCS] 서버에 있는 .env 파일을 참조하도록 변경 (#30)

- .github/workflows/cd.yml
> [DOCS] CD.yml 수정

- .github/workflows/cd.yml
* [DOCS] 서버에 있는 .env 파일을 참조하도록 변경 (#30)
* [FEAT] CD.yml 수정 (#30)
* [FEAT] Merge 했을 때만 배포되도록 변경 (#30)
* [FEAT] 볼륨마운트 추가 (#30)
>
>
> [DEPLOY] 테스트 배포

- .github/workflows/cd.yml
- build.gradle.kts
> CD.yml에서 명시적으로 빌드하도록 설정했습니다.
>
> [FIX] RestDocs 오류 수정

- .github/workflows/cd.yml
- build.gradle.kts
> [DEPLOY] RestDocs 오류 수정 배포

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- build.gradle.kts
- core/core-api/build.gradle.kts
> [FIX] spring rest docs

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- core/core-api/build.gradle.kts
* [FEAT] 배포 시 명시적으로 restDocsTest asciidoctor 를 실행하도록 변경 (#39)
* [FEAT] 스니펫 생성위치 확인 테스트 (#39)
* [FEAT] 2차 테스트 (#39)
>
>
> [DEPLOY] spring rest docs (#42)

- core/core-api/build.gradle.kts
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/WebMvcConfig.kt
> - RestDoc Html 반환을 위한 WebMvc 를 enable 했습니다.
> closes #44
> [FEAT]: WebMvcConfig 추가

- core/core-api/build.gradle.kts
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/WebMvcConfig.kt
* [FEAT]: WebMvcConfig 추가
* [FIX]: gradle 수정
>
>
> [DEPLOY]: WebMvcConfig 추가 (#45)

- .github/workflows/cd.yml
- build.gradle.kts
> [HOTFIX] build.gradle.kts 의존성 수정

- core/core-api/build.gradle.kts
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/WebMvcConfig.kt
> [DEPLOY] 배포오류 핫픽스

- build.gradle.kts
- core/core-api/build.gradle.kts
> [HOTFIX] build.gradle.kts 의존성 수정 (#47)

- build.gradle.kts
- core/core-api/build.gradle.kts
> [HOTFIX] build.gradle.kts 의존성 수정 (#47) (#50)

- .github/workflows/cd.yml
- .gitignore
- build.gradle.kts
- core/core-api/build.gradle.kts
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/FaviconController.kt
> [Hotfix] build gradle fix

- .github/workflows/cd.yml
- .gitignore
- core/core-api/build.gradle.kts
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/FaviconController.kt
* [HOTFIX] build.gradle.kts 의존성 수정 (#47)
* [HOTFIX] build.gradle.kts 의존성 수정 (#47)
* [HOTFIX] build.gradle.kts 의존성 수정 (#47)
* [FEAT] favicon Controller 추가 (#47)
* [FEAT] .gitignore 추가 (#47)
>
>
> [Hotfix] build gradle fix (#53)

- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/JwtSecurityConfig.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConstants.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/WebMvcConfig.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/jwt/JwtFilter.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/log/RequestResponseLoggingFilter.kt
- support/logging/build.gradle.kts
- support/logging/src/main/resources/logback/logback-live.xml
- support/logging/src/main/resources/logback/logback-local.xml
> LogBack 설정 완료했습니다. log/ 파일로 생성되는것까지 확인했습니다.
현재 로컬에만 적용해놓은 상태이고 ELK 스택까지 전부 성공한 후 바꿔서 다시 올리겠습니다.
> 추가로 permitAll url의 경우 자꾸 jwt토큰이 없다는 오류가 로그에 남길래 바로 doFilter 진행하도록 수정했습니다.
수정 과정에서 URL 재사용 가능성이 있어 한곳에 모아놨습니다.
> [FEAT] logback 설정한다.

- core/core-api/src/docs/asciidoc/auth.adoc
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/AuthController.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/domain/JwtValidator.kt
- core/core-api/src/test/kotlin/com/myongjiway/core/auth/controller/AuthControllerTest.kt
- core/core-api/src/test/kotlin/com/myongjiway/token/TokenTypeTest.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorCode.kt
- core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorType.kt
- core/core-domain/src/main/kotlin/com/myongjiway/token/TokenProcessor.kt
- core/core-domain/src/main/kotlin/com/myongjiway/token/TokenRepository.kt
- core/core-domain/src/main/kotlin/com/myongjiway/token/TokenService.kt
- core/core-domain/src/test/kotlin/com/myongjiway/token/TokenProcessorTest.kt
- core/core-domain/src/test/kotlin/com/myongjiway/token/TokenServiceTest.kt
- storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenCoreRepository.kt
- storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenJpaRepository.kt
- storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/token/TokenCoreRepositoryTest.kt
>- logout api 구현하였습니다.
>closes #59
> [FEAT]: Logout API 구현

- .github/workflows/cd.yml
- support/logging/src/main/resources/logback/logback-live.xml
- support/logging/src/main/resources/logback/logback-local.xml
>  ELK로 구성했으나 기본사양이 CPU 코어 2개 이상, 4GB Ram이 필요해서 Loki, Grapana, Promtail 스택을 사용해서 구현했습니다.
또한 기존 docker 컨테이너 안에서 생성되던 log 파일을 host 머신에서 생성되게 변경했습니다.
>
> [FEAT] LG Stack Logging (#57)

- support/logging/src/main/resources/logback/logback-live.xml
* [FEAT] 볼륨마운트 추가 Docker 컨테이너가 아닌 호스트 머신에서 생성되도록 변경 (#57)
* [FEAT] 엡펜더 이름 수정 (#57)
>
>
> [DEPLOY] 배포 (#71)

- core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
* [FEAT] 사용하지 않는 파일 제거 (#74)
* [FEAT] 로그 간소화 추후 필요 시 추가 (#74)
* [FEAT] Prometheus 와 같은 network 에서 작동하도록 변경(#74)
* [FEAT] Notice 응답값 시분초 안나오도록 변경 (#74)
* [FIX] 프로메테우스 URL PermitAll 로 변경 (#74)
>
>
> [DEPLOY] 배포 

- core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/NoticeAdminController.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/NoticeController.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/v1/request/NoticeRequest.kt
- core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/v1/response/NoticeResponse.kt
- core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeAdminControllerDocsTest.kt
- core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeControllerDocsTest.kt
- core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeCreateControllerTest.kt
- core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeUpdateControllerTest.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorCode.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorType.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreException.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/Notice.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeCreator.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeDeleter.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeFinder.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeMetadata.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeRepository.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeService.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeUpdater.kt
- core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeView.kt
- core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeCreatorTest.kt
- core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeFinderTest.kt
- core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeUpdaterTest.kt
- storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeCoreRepository.kt
- storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeEntity.kt
- storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/UserNoticeEntity.kt
> null 값을 최소화하고 필요없는 부분 바꿨습니다.
응답용 도메인을 생성했습니다.
>
> [REFACTOR] 공지사항 리팩토링

- .github/workflows/cd.yml
> [CHORE] 타임존 서울로 변경 (#87)

- core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/log/RequestResponseLoggingFilter.kt
- support/logging/src/main/resources/logback/logback-live.xml
> [REFACTOR] 응답 로깅 삭제, 로깅 필드 추가 (#83)

- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleApi.kt
- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleClient.kt
- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleRestClientConfig.kt
- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKeyResult.kt
- clients/client-apple/src/main/resources/client-apple.yml
- clients/client-apple/src/test/kotlin/com/myongjiway/ClientAppleContextTest.kt
- clients/client-apple/src/test/kotlin/com/myongjiway/ClientAppleTestApplication.kt
- clients/client-apple/src/test/resources/application.yml
- clients/client-kakao/src/test/kotlin/com/myongjiway/ClientKakaoContextTest.kt
- clients/client-kakao/src/test/kotlin/com/myongjiway/ClientKakaoTestApplication.kt
> - apple token 검증을 위한 public key 발급 api 연동하였습니다.
>
> [FEAT]: apple public key 발급 API 연동

- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleApi.kt
- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleClient.kt
- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleRestClientConfig.kt
- clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKeyResult.kt
- clients/client-apple/src/main/resources/client-apple.yml
- clients/client-apple/src/test/kotlin/com/myongjiway/ClientAppleContextTest.kt
- clients/client-apple/src/test/kotlin/com/myongjiway/ClientAppleTestApplication.kt
- clients/client-apple/src/test/resources/application.yml
- clients/client-kakao/src/test/kotlin/com/myongjiway/ClientKakaoContextTest.kt
- clients/client-kakao/src/test/kotlin/com/myongjiway/ClientKakaoTestApplication.kt
* [FEAT]: Apple Client 구성
* [FEAT]: public key 발급 API 연동
>
>
> [DEPLOY] apple public key 발급 API 연동 (#91)

- support/logging/src/main/resources/logback/logback-live.xml
> [FIX] logging 에러 수정

- support/logging/src/main/resources/logback/logback-live.xml
* [refactor] 응답 로깅 삭제, 로깅 필드 추가 (#83)
* [fix] 로깅 에러 수정 (#83)
>
>
> [FIX] logging 에러 수정 (#93)

- support/logging/src/main/resources/logback/logback-live.xml
- support/logging/src/main/resources/logback/logback-local.xml
* [refactor] 응답 로깅 삭제, 로깅 필드 추가 (#83)
* [fix] 로깅 에러 수정 (#83)
* [REFACTOR] 기존 필터에서 처리하던 것을 AOP 로 분리 (#83)
* [REFACTOR] API Advice 에서 처리하던 것을 AOP 로 분리 (#83)
* [REFACTOR] Authentication 로그는 Filter 쪽에서 처리하도록 변경 (#83)
* [REFACTOR] 로깅 관련 xml 수정 (#83)
* [REFACTOR] LoggingAspect 구현 (#83)
* [FIX] Root 를 정수로 인식해 Short 로 변경 (#83)
>
>
> [DEPLOY] logging (#97)

- core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestLoggingAspect.kt
- support/logging/src/main/resources/logback/logback-live.xml
- support/logging/src/main/resources/logback/logback-local.xml
> 로깅에 값 추가했습니다. 
host: 요청이 들어온 호스트명을 기록하여, 동일한 백엔드 서버로 요청이 들어오더라도 어떤 도메인이나 서브도메인으로 요청이 왔는지 추적할 수 있습니다.
X-Forwarded-For: 사용자가 거쳐온 프록시 서버들의 IP 주소 목록을 확인할 수 있어, 사용자의 경로를 추적하거나 중간에 어떤 프록시 서버를 거쳤는지 파악하는데 쓰입니다.
X-Forwarded-Proto: 요청이 HTTP 또는 HTTPS 중 어느 프로토콜로 이루어졌는지 확인할 수 있습니다.
ip가 실제 사용자의 ip를 반영하도록 수정했습니다.
따라서 nginx 수정했습니다. ssl 설정 하는 부분인 location 쪽에 header 정보 추가했습니다.
응답 로거 추가하고 nanoTime으로 측정하여 초로 변환하고 소수점 3자리 수 까지 출력하도록 했습니다.
>
> [FEAT] logging

- support/logging/src/main/resources/logback/logback-live.xml
- support/logging/src/main/resources/logback/logback-local.xml
> [FIX] 쉼표 수정 (#113)

- support/logging/src/main/resources/logback/logback-live.xml
- support/logging/src/main/resources/logback/logback-local.xml
> [DEPLOY] 재배포
